export const FETCH_PAINTINGS = 'FETCH_PAINTINGS';
export const SELECT_ACTIVE_PAINTING = 'SELECT_ACTIVE_PAINTING';
export const DELETE_PAINTING = 'DELETE_PAINTING';
export const SELECT_MUSEUM = 'SELECT_MUSEUM';
export const DESELECT_MUSEUM = 'DESELECT_MUSEUM';
